en:
  my_app:
    errors:
      taken: 'is already taken'